import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { spiralLayout } from './kernel.mjs';

// The real ledger, generated by lessonsfold-cli.mjs and machine-copied into this repo (never
// hand-typed) — see ledger-snapshot.json's own provenance header.
const REAL = JSON.parse(readFileSync(new URL('./ledger-snapshot.json', import.meta.url), 'utf8'));

// ── input validation ──
test('rejects a non-array, non-{lessons} input', () => {
  assert.equal(spiralLayout('nope').ok, false);
  assert.equal(spiralLayout(42).ok, false);
  assert.equal(spiralLayout(null).ok, false);
  assert.equal(spiralLayout(undefined).ok, false);
});
test('accepts a bare array', () => {
  assert.equal(spiralLayout([{ title: 'A', count: 1 }]).ok, true);
});
test('accepts an object with a .lessons array (the real ledger file shape)', () => {
  assert.equal(spiralLayout({ lessons: [{ title: 'A', count: 1 }] }).ok, true);
});
test('a bare array and the equivalent {lessons:[...]} wrapper produce identical output', () => {
  const data = [{ title: 'B', count: 2 }, { title: 'A', count: 5 }];
  const a = spiralLayout(data);
  const b = spiralLayout({ lessons: data });
  assert.deepEqual(a, b);
});
test('rejects an entry that is not an object', () => {
  assert.equal(spiralLayout(['not an object']).ok, false);
  assert.equal(spiralLayout([null]).ok, false);
});
test('rejects a missing or empty title, isolated from the count check', () => {
  assert.match(spiralLayout([{ count: 1 }]).why, /title/);
  assert.match(spiralLayout([{ title: '', count: 1 }]).why, /title/);
  assert.match(spiralLayout([{ title: '   ', count: 1 }]).why, /title/);
});
test('rejects a non-string title', () => {
  assert.match(spiralLayout([{ title: 42, count: 1 }]).why, /title/);
});
test('rejects a missing, non-integer, zero, or negative count, isolated from the title check', () => {
  assert.match(spiralLayout([{ title: 'A' }]).why, /count/);
  assert.match(spiralLayout([{ title: 'A', count: 1.5 }]).why, /count/);
  assert.match(spiralLayout([{ title: 'A', count: 0 }]).why, /count/);
  assert.match(spiralLayout([{ title: 'A', count: -1 }]).why, /count/);
});
test('rejects a duplicate title (bijection would break)', () => {
  const r = spiralLayout([{ title: 'A', count: 1 }, { title: 'A', count: 2 }]);
  assert.equal(r.ok, false);
  assert.match(r.why, /duplicate/);
});
test('an empty ledger is valid — zero glyphs, not a refusal', () => {
  assert.deepEqual(spiralLayout([]), { ok: true, glyphs: [] });
  assert.deepEqual(spiralLayout({ lessons: [] }), { ok: true, glyphs: [] });
});

// ── BIJECTION: every lesson maps to exactly one glyph, none lost, none invented ──
test('bijection: glyph count === lesson count, for the real ledger', () => {
  const r = spiralLayout(REAL);
  assert.equal(r.ok, true);
  assert.equal(r.glyphs.length, REAL.lessons.length);
});
test('bijection: every real lesson title appears in exactly one glyph, and vice versa', () => {
  const r = spiralLayout(REAL);
  const inputTitles = new Set(REAL.lessons.map((l) => l.title));
  const outputTitles = r.glyphs.map((g) => g.title);
  assert.equal(outputTitles.length, new Set(outputTitles).size, 'no glyph title repeats');
  assert.equal(outputTitles.length, inputTitles.size);
  for (const t of outputTitles) assert.equal(inputTitles.has(t), true, `glyph title "${t}" was not in the input`);
});
test('bijection holds for synthetic sizes too: 1, 2, 50 lessons', () => {
  for (const n of [1, 2, 50]) {
    const data = Array.from({ length: n }, (_, i) => ({ title: 'L' + i, count: (i % 5) + 1 }));
    const r = spiralLayout(data);
    assert.equal(r.ok, true);
    assert.equal(r.glyphs.length, n);
  }
});

// ── MONOTONICITY: size is a monotonic function of count, checkable not asserted ──
test('monotonicity: the real ledger\'s biggest glyph IS the most-rediscovered lesson (HysteresisGate x7)', () => {
  const r = spiralLayout(REAL);
  const biggest = r.glyphs.reduce((a, b) => (b.size > a.size ? b : a));
  assert.equal(biggest.title, 'HysteresisGate');
  assert.equal(biggest.count, 7);
  assert.equal(biggest.rank, 0);
});
test('monotonicity: higher count never gets a smaller-or-equal size than a lower count, across the whole real ledger', () => {
  const r = spiralLayout(REAL);
  const byRank = r.glyphs.slice().sort((a, b) => a.rank - b.rank);
  for (let i = 1; i < byRank.length; i++) {
    const prev = byRank[i - 1], cur = byRank[i];
    if (cur.count < prev.count) assert.ok(cur.size < prev.size, `rank ${i} (count ${cur.count}) should be strictly smaller than rank ${i - 1} (count ${prev.count})`);
    else assert.equal(cur.size, prev.size, `equal counts (${cur.count}) at adjacent ranks must get equal size`);
  }
});
test('monotonicity: all five real lessons tied at count=2 get EXACTLY the same size', () => {
  const r = spiralLayout(REAL);
  const tied = r.glyphs.filter((g) => g.count === 2);
  assert.equal(tied.length, 5); // MaskFold, NoiseBudget, PulseDebounce, QuorumMask Aggregate, TopoFold
  const sizes = new Set(tied.map((g) => g.size));
  assert.equal(sizes.size, 1, 'every count=2 glyph must share one identical size');
});
test('monotonicity: a ledger where every lesson is tied gives every glyph the same size (constant is still monotonic)', () => {
  const r = spiralLayout([{ title: 'A', count: 3 }, { title: 'B', count: 3 }, { title: 'C', count: 3 }]);
  const sizes = new Set(r.glyphs.map((g) => g.size));
  assert.equal(sizes.size, 1);
});
test('monotonicity: a single-lesson ledger never divides by zero and returns a valid size', () => {
  const r = spiralLayout([{ title: 'Solo', count: 9 }]);
  assert.equal(r.ok, true);
  assert.equal(Number.isFinite(r.glyphs[0].size), true);
});

// ── DETERMINISM: same ledger, any input order, byte-identical output ──
test('determinism: shuffled input order produces IDENTICAL output to the canonical order', () => {
  const a = spiralLayout(REAL);
  const shuffled = { lessons: REAL.lessons.slice().reverse() };
  const b = spiralLayout(shuffled);
  assert.deepEqual(a, b);
});
test('determinism: two separate calls on the same data produce byte-identical JSON', () => {
  const a = JSON.stringify(spiralLayout(REAL));
  const b = JSON.stringify(spiralLayout(REAL));
  assert.equal(a, b);
});
test('determinism: canonical order is count desc, then title asc on ties (same tie-break as lessonsfold.mjs)', () => {
  const data = [{ title: 'Zed', count: 2 }, { title: 'Alpha', count: 2 }, { title: 'Mid', count: 5 }];
  const r = spiralLayout(data);
  assert.deepEqual(r.glyphs.map((g) => g.title), ['Mid', 'Alpha', 'Zed']);
});

// ── placement: reuses golden-placer's exact place2D formula, pinned numerically ──
test('placement: rank 0 of a 3-lesson ledger matches golden-placer\'s place2D(0,3) exactly', () => {
  // r = sqrt((0+0.5)/3) = sqrt(1/6); theta = 2*PI*G*0 = 0 -> x=r,y=0
  const r = spiralLayout([{ title: 'A', count: 3 }, { title: 'B', count: 2 }, { title: 'C', count: 1 }]);
  const g0 = r.glyphs.find((g) => g.rank === 0);
  const expectedR = Math.sqrt(0.5 / 3);
  assert.ok(Math.abs(g0.x - expectedR) < 1e-12);
  assert.ok(Math.abs(g0.y - 0) < 1e-12);
});
test('placement: rank 1\'s angle uses the golden rotation G=1/phi exactly, not just radius', () => {
  // rank 0 always has theta=0 regardless of G (i=0 zeroes it out) — this pins rank 1 specifically,
  // with G recomputed independently ((sqrt(5)-1)/2, a different arithmetic path to the same
  // constant than the kernel's own PHI-1) so a wrong rotation constant can't hide behind a
  // radius-only or rank-0-only check.
  const independentG = (Math.sqrt(5) - 1) / 2;
  const r = spiralLayout([{ title: 'A', count: 3 }, { title: 'B', count: 2 }, { title: 'C', count: 1 }]);
  const g1 = r.glyphs.find((g) => g.rank === 1);
  const expectedR = Math.sqrt(1.5 / 3);
  const theta = 2 * Math.PI * independentG * 1;
  assert.ok(Math.abs(g1.x - expectedR * Math.cos(theta)) < 1e-12);
  assert.ok(Math.abs(g1.y - expectedR * Math.sin(theta)) < 1e-12);
});
test('placement: rank 0 is always nearest the center (smallest radius) among all glyphs', () => {
  const r = spiralLayout(REAL);
  const radius = (g) => Math.sqrt(g.x * g.x + g.y * g.y);
  const g0 = r.glyphs.find((g) => g.rank === 0);
  for (const g of r.glyphs) if (g.rank !== 0) assert.ok(radius(g0) <= radius(g) + 1e-12);
});

// ── TOTAL / fuzz: garbage never throws ──
test('fuzz: garbage top-level inputs never throw', () => {
  const garbage = [undefined, null, {}, [], () => {}, Symbol('x'), NaN, Infinity, '', '0', true, false, 0, new Map(), new Date(), { lessons: 'not an array' }, { lessons: null }];
  for (const g of garbage) assert.doesNotThrow(() => spiralLayout(g));
});
test('fuzz: garbage lesson entries never throw, always refuse cleanly', () => {
  const garbageEntries = [null, undefined, 1, 'x', [], () => {}, { title: null, count: 1 }, { title: 'A', count: 'x' }, { title: 'A', count: NaN }, { title: 'A', count: Infinity }, { title: 'A', count: -5 }];
  for (const e of garbageEntries) {
    const r = spiralLayout([e]);
    assert.equal(r.ok, false);
  }
});
test('fuzz: 300 random valid ledgers of random size all satisfy bijection + monotonicity', () => {
  let seed = 424242;
  const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed; };
  let failures = 0;
  for (let trial = 0; trial < 300; trial++) {
    const n = rnd() % 40; // 0..39 lessons
    const data = Array.from({ length: n }, (_, i) => ({ title: 'T' + i + '-' + (rnd() % 1000), count: (rnd() % 20) + 1 }));
    const titles = new Set(data.map((d) => d.title));
    if (titles.size !== data.length) continue; // random collision — vanishingly rare, just skip this trial
    const r = spiralLayout(data);
    if (!r.ok) { failures++; continue; }
    if (r.glyphs.length !== data.length) failures++;
    const byRank = r.glyphs.slice().sort((a, b) => a.rank - b.rank);
    for (let i = 1; i < byRank.length; i++) {
      if (byRank[i].count > byRank[i - 1].count) failures++;
      if (byRank[i].count === byRank[i - 1].count && byRank[i].size !== byRank[i - 1].size) failures++;
      if (byRank[i].count < byRank[i - 1].count && byRank[i].size >= byRank[i - 1].size) failures++;
    }
  }
  assert.equal(failures, 0, failures + ' fuzzed ledgers violated bijection or monotonicity');
});
